/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Paul
{
  public enum ResultUserLogin
  {
    Success = 1,
    Diff = 11,
    Error = 99,
  }
}
