/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Paul
{
  public enum UserStatusType
  {
    ACTIVE = 1,
    BLOCKED = 2,
    MAINTENANCE = 3,
    LEAVE = 4,
    LOGOUT = 5,
  }
}
